---
version: "3"
services:
 devopsdb:
   image: shaikmustafa/mynewapp:dbimage
   ports:
     - "3306:3306"
   deploy:
     replicas: 4

 application:
   image: shaikmustafa/mynewapp:appimage
   ports:
     - "1111:8080"
   deploy:
     replicas: 4
   depends_on:
     - "devopsdb"
